-- Pedizza: foundation. Fail rather than overwrite an incompatible existing schema.
create schema if not exists private;
revoke all on schema private from public;
create table public.tenants (id uuid primary key default gen_random_uuid(), name text not null check(length(name) between 2 and 120), slug text not null unique, manually_suspended boolean not null default false, suspension_reason text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null check(length(name) between 1 and 120), phone text, avatar_url text, blocked boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.tenant_members (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), user_id uuid not null references public.profiles(id), role text not null check(role in ('owner','admin','manager','attendant','kitchen','custom')), active boolean not null default true, created_at timestamptz not null default now(), unique(tenant_id,user_id), unique(tenant_id,id));
create table public.permissions (code text primary key, description text not null);
create table public.role_permissions (role text not null, permission text not null references public.permissions(code), primary key(role,permission));
create table public.member_permissions (tenant_id uuid not null, member_id uuid not null, permission text not null references public.permissions(code), allowed boolean not null, primary key(member_id,permission), foreign key(tenant_id,member_id) references public.tenant_members(tenant_id,id));
create table private.super_admins (user_id uuid primary key references public.profiles(id));
create table public.subscription_plans (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, price_cents integer not null check(price_cents>=0), billing_interval text not null default 'monthly', active boolean not null default true);
insert into public.subscription_plans(code,name,price_cents) values('pedizza_monthly','Pedizza',4700);
create table public.subscriptions (id uuid primary key default gen_random_uuid(), tenant_id uuid not null unique references public.tenants(id), plan_id uuid not null references public.subscription_plans(id), status text not null default 'pending' check(status in ('pending','active','past_due','suspended','cancelled')), provider_subscription_id text unique, current_period_end timestamptz, provider_updated_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), tenant_id uuid references public.tenants(id), user_id uuid references public.profiles(id), action text not null, resource_type text not null, resource_id uuid, metadata jsonb not null default '{}', ip_address inet, user_agent text, created_at timestamptz not null default now());
create function private.member_of(t uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.tenant_members m join public.profiles p on p.id=m.user_id where m.tenant_id=t and m.user_id=(select auth.uid()) and m.active and not p.blocked) $$;
create function private.has_permission(t uuid, p text) returns boolean language sql stable security definer set search_path='' as $$
select exists(select 1 from public.tenant_members m join public.profiles u on u.id=m.user_id where m.tenant_id=t and m.user_id=(select auth.uid()) and m.active and not u.blocked and exists(select 1 from public.permissions where code=p) and (m.role='owner' or coalesce((select allowed from public.member_permissions where member_id=m.id and permission=p),exists(select 1 from public.role_permissions where role=m.role and permission=p)))) $$;
create function private.subscription_active(t uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.subscriptions s join public.tenants t1 on t1.id=s.tenant_id where s.tenant_id=t and s.status='active' and s.current_period_end>now() and not t1.manually_suspended) $$;
create function public.has_permission(tenant uuid, permission text) returns boolean language sql stable security invoker set search_path='' as $$ select private.has_permission(tenant,permission) $$;
create function public.is_super_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from private.super_admins s join public.profiles p on p.id=s.user_id where s.user_id=(select auth.uid()) and not p.blocked) $$;
revoke all on all functions in schema private from public;
grant usage on schema private to authenticated;
grant execute on function private.member_of(uuid),private.has_permission(uuid,text),private.subscription_active(uuid) to authenticated;
revoke all on function public.has_permission(uuid,text),public.is_super_admin() from public;
grant execute on function public.has_permission(uuid,text),public.is_super_admin() to authenticated;
create index tenant_members_user_active on public.tenant_members(user_id,tenant_id) where active;
create index audit_logs_tenant_created on public.audit_logs(tenant_id,created_at desc);
create function private.touch_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now(); return new; end $$;
insert into public.permissions(code,description) values('dashboard.view','dashboard.view');
insert into public.role_permissions values('admin','dashboard.view');
insert into public.role_permissions values('manager','dashboard.view');
insert into public.role_permissions values('attendant','dashboard.view');
insert into public.permissions(code,description) values('dashboard.financial','dashboard.financial');
insert into public.role_permissions values('admin','dashboard.financial');
insert into public.role_permissions values('manager','dashboard.financial');
insert into public.permissions(code,description) values('orders.view','orders.view');
insert into public.role_permissions values('admin','orders.view');
insert into public.role_permissions values('manager','orders.view');
insert into public.role_permissions values('attendant','orders.view');
insert into public.role_permissions values('kitchen','orders.view');
insert into public.permissions(code,description) values('orders.accept','orders.accept');
insert into public.role_permissions values('admin','orders.accept');
insert into public.role_permissions values('manager','orders.accept');
insert into public.role_permissions values('attendant','orders.accept');
insert into public.permissions(code,description) values('orders.refuse','orders.refuse');
insert into public.role_permissions values('admin','orders.refuse');
insert into public.role_permissions values('manager','orders.refuse');
insert into public.permissions(code,description) values('orders.update_status','orders.update_status');
insert into public.role_permissions values('admin','orders.update_status');
insert into public.role_permissions values('manager','orders.update_status');
insert into public.role_permissions values('attendant','orders.update_status');
insert into public.role_permissions values('kitchen','orders.update_status');
insert into public.permissions(code,description) values('orders.cancel','orders.cancel');
insert into public.role_permissions values('admin','orders.cancel');
insert into public.role_permissions values('manager','orders.cancel');
insert into public.permissions(code,description) values('orders.print','orders.print');
insert into public.role_permissions values('admin','orders.print');
insert into public.role_permissions values('manager','orders.print');
insert into public.role_permissions values('attendant','orders.print');
insert into public.role_permissions values('kitchen','orders.print');
insert into public.permissions(code,description) values('conversations.view','conversations.view');
insert into public.role_permissions values('admin','conversations.view');
insert into public.role_permissions values('manager','conversations.view');
insert into public.role_permissions values('attendant','conversations.view');
insert into public.permissions(code,description) values('conversations.send','conversations.send');
insert into public.role_permissions values('admin','conversations.send');
insert into public.role_permissions values('manager','conversations.send');
insert into public.role_permissions values('attendant','conversations.send');
insert into public.permissions(code,description) values('conversations.assign','conversations.assign');
insert into public.role_permissions values('admin','conversations.assign');
insert into public.role_permissions values('manager','conversations.assign');
insert into public.role_permissions values('attendant','conversations.assign');
insert into public.permissions(code,description) values('conversations.resume_bot','conversations.resume_bot');
insert into public.role_permissions values('admin','conversations.resume_bot');
insert into public.role_permissions values('manager','conversations.resume_bot');
insert into public.role_permissions values('attendant','conversations.resume_bot');
insert into public.permissions(code,description) values('conversations.archive','conversations.archive');
insert into public.role_permissions values('admin','conversations.archive');
insert into public.role_permissions values('manager','conversations.archive');
insert into public.permissions(code,description) values('customers.view','customers.view');
insert into public.role_permissions values('admin','customers.view');
insert into public.role_permissions values('manager','customers.view');
insert into public.role_permissions values('attendant','customers.view');
insert into public.permissions(code,description) values('customers.edit','customers.edit');
insert into public.role_permissions values('admin','customers.edit');
insert into public.role_permissions values('manager','customers.edit');
insert into public.role_permissions values('attendant','customers.edit');
insert into public.permissions(code,description) values('customers.archive','customers.archive');
insert into public.role_permissions values('admin','customers.archive');
insert into public.role_permissions values('manager','customers.archive');
insert into public.permissions(code,description) values('campaigns.view','campaigns.view');
insert into public.role_permissions values('admin','campaigns.view');
insert into public.role_permissions values('manager','campaigns.view');
insert into public.permissions(code,description) values('campaigns.edit','campaigns.edit');
insert into public.role_permissions values('admin','campaigns.edit');
insert into public.role_permissions values('manager','campaigns.edit');
insert into public.permissions(code,description) values('campaigns.archive','campaigns.archive');
insert into public.role_permissions values('admin','campaigns.archive');
insert into public.role_permissions values('manager','campaigns.archive');
insert into public.permissions(code,description) values('menu.view','menu.view');
insert into public.role_permissions values('admin','menu.view');
insert into public.role_permissions values('manager','menu.view');
insert into public.permissions(code,description) values('menu.edit','menu.edit');
insert into public.role_permissions values('admin','menu.edit');
insert into public.role_permissions values('manager','menu.edit');
insert into public.permissions(code,description) values('menu.archive','menu.archive');
insert into public.role_permissions values('admin','menu.archive');
insert into public.role_permissions values('manager','menu.archive');
insert into public.permissions(code,description) values('delivery.view','delivery.view');
insert into public.role_permissions values('admin','delivery.view');
insert into public.role_permissions values('manager','delivery.view');
insert into public.permissions(code,description) values('delivery.edit','delivery.edit');
insert into public.role_permissions values('admin','delivery.edit');
insert into public.role_permissions values('manager','delivery.edit');
insert into public.permissions(code,description) values('team.view','team.view');
insert into public.role_permissions values('admin','team.view');
insert into public.permissions(code,description) values('team.invite','team.invite');
insert into public.role_permissions values('admin','team.invite');
insert into public.permissions(code,description) values('team.manage_permissions','team.manage_permissions');
insert into public.role_permissions values('admin','team.manage_permissions');
insert into public.permissions(code,description) values('team.deactivate','team.deactivate');
insert into public.role_permissions values('admin','team.deactivate');
insert into public.permissions(code,description) values('settings.view','settings.view');
insert into public.role_permissions values('admin','settings.view');
insert into public.permissions(code,description) values('settings.edit','settings.edit');
insert into public.role_permissions values('admin','settings.edit');
insert into public.permissions(code,description) values('whatsapp.view','whatsapp.view');
insert into public.role_permissions values('admin','whatsapp.view');
insert into public.permissions(code,description) values('whatsapp.manage','whatsapp.manage');
insert into public.role_permissions values('admin','whatsapp.manage');
insert into public.permissions(code,description) values('payments.view','payments.view');
insert into public.role_permissions values('admin','payments.view');
insert into public.permissions(code,description) values('payments.manage','payments.manage');
insert into public.role_permissions values('admin','payments.manage');
insert into public.permissions(code,description) values('payments.confirm_manual','payments.confirm_manual');
insert into public.role_permissions values('admin','payments.confirm_manual');
insert into public.permissions(code,description) values('printing.view','printing.view');
insert into public.role_permissions values('admin','printing.view');
insert into public.role_permissions values('manager','printing.view');
insert into public.permissions(code,description) values('printing.manage','printing.manage');
insert into public.role_permissions values('admin','printing.manage');
insert into public.role_permissions values('manager','printing.manage');
insert into public.permissions(code,description) values('notifications.view','notifications.view');
insert into public.role_permissions values('admin','notifications.view');
insert into public.role_permissions values('manager','notifications.view');
insert into public.role_permissions values('attendant','notifications.view');
insert into public.role_permissions values('kitchen','notifications.view');
insert into public.permissions(code,description) values('notifications.manage','notifications.manage');
insert into public.role_permissions values('admin','notifications.manage');
insert into public.role_permissions values('manager','notifications.manage');
insert into public.permissions(code,description) values('subscription.view','subscription.view');
insert into public.role_permissions values('admin','subscription.view');
insert into public.permissions(code,description) values('subscription.manage','subscription.manage');
insert into public.role_permissions values('admin','subscription.manage');
insert into public.permissions(code,description) values('audit.view','audit.view');
insert into public.role_permissions values('admin','audit.view');

create function private.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ declare t uuid; store_name text; begin
 insert into public.profiles(id,name) values(new.id,left(coalesce(nullif(trim(new.raw_user_meta_data->>'name'),''),'Usuário'),120));
 store_name=trim(new.raw_user_meta_data->>'store_name');
 if store_name is not null and length(store_name) between 2 and 120 then
  insert into public.tenants(name,slug) values(store_name,'loja-'||replace(gen_random_uuid()::text,'-','')) returning id into t;
  insert into public.tenant_members(tenant_id,user_id,role) values(t,new.id,'owner');
  insert into public.subscriptions(tenant_id,plan_id) select t,id from public.subscription_plans where code='pedizza_monthly';
 end if;
 return new;
end $$;
create trigger pedizza_on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();
