-- Immutable tenancy, range validation and private-table defence in depth.
create function private.immutable_tenant() returns trigger language plpgsql set search_path='' as $$ begin if new.tenant_id<>old.tenant_id then raise exception 'tenant_id is immutable' using errcode='23514'; end if;return new;end $$;
do $$ declare r record;begin for r in select table_name from information_schema.columns where table_schema='public' and column_name='tenant_id' loop execute format('create trigger immutable_tenant before update on public.%I for each row execute function private.immutable_tenant()',r.table_name);end loop;for r in select tablename from pg_tables where schemaname='private' loop execute format('alter table private.%I enable row level security',r.tablename);end loop;end $$;
create function private.check_distance_range() returns trigger language plpgsql security definer set search_path='' as $$ begin perform 1 from public.tenants where id=new.tenant_id for update;if new.active and exists(select 1 from public.delivery_distance_fees where tenant_id=new.tenant_id and id<>new.id and active and min_meters<new.max_meters and max_meters>new.min_meters) then raise exception 'overlapping distance range' using errcode='23514';end if;return new;end $$;
create trigger check_distance_range before insert or update on public.delivery_distance_fees for each row execute function private.check_distance_range();
create function private.check_item_price_category() returns trigger language plpgsql security definer set search_path='' as $$ begin if not exists(select 1 from public.menu_items i join public.menu_sizes s on s.tenant_id=i.tenant_id and s.category_id=i.category_id where i.id=new.item_id and i.tenant_id=new.tenant_id and s.id=new.size_id) then raise exception 'category mismatch' using errcode='23514';end if;return new;end $$;
create trigger check_item_price_category before insert or update on public.menu_item_prices for each row execute function private.check_item_price_category();
create function private.check_business_hours() returns trigger language plpgsql security definer set search_path='' as $$ declare ns integer;ne integer;begin
 perform 1 from public.tenants where id=new.tenant_id for update;
 ns=new.day_of_week*86400+extract(epoch from new.start_time)::integer;ne=new.day_of_week*86400+extract(epoch from new.end_time)::integer;if ne<=ns then ne=ne+86400;end if;
 if exists(select 1 from public.store_business_hours h cross join (values(-604800),(0),(604800)) w(shift) where h.tenant_id=new.tenant_id and h.id<>new.id and ns<h.day_of_week*86400+extract(epoch from h.end_time)::integer+case when h.end_time<=h.start_time then 86400 else 0 end+w.shift and h.day_of_week*86400+extract(epoch from h.start_time)::integer+w.shift<ne) then raise exception 'overlapping business hours' using errcode='23514';end if;return new;
end $$;
create trigger check_business_hours before insert or update on public.store_business_hours for each row execute function private.check_business_hours();
revoke all on function private.immutable_tenant(),private.check_distance_range(),private.check_item_price_category(),private.check_business_hours(),private.handle_new_user(),private.initialize_store(),private.touch_updated_at() from public;
