-- RLS, minimum grants and server-only state.
alter table public.tenants enable row level security;
revoke all on public.tenants from anon,authenticated;
grant select on public.tenants to authenticated;
alter table public.profiles enable row level security;
revoke all on public.profiles from anon,authenticated;
grant select on public.profiles to authenticated;
alter table public.tenant_members enable row level security;
revoke all on public.tenant_members from anon,authenticated;
grant select on public.tenant_members to authenticated;
alter table public.permissions enable row level security;
revoke all on public.permissions from anon,authenticated;
grant select on public.permissions to authenticated;
alter table public.role_permissions enable row level security;
revoke all on public.role_permissions from anon,authenticated;
grant select on public.role_permissions to authenticated;
alter table public.member_permissions enable row level security;
revoke all on public.member_permissions from anon,authenticated;
grant select on public.member_permissions to authenticated;
alter table public.subscription_plans enable row level security;
revoke all on public.subscription_plans from anon,authenticated;
grant select on public.subscription_plans to authenticated;
alter table public.subscriptions enable row level security;
revoke all on public.subscriptions from anon,authenticated;
grant select on public.subscriptions to authenticated;
alter table public.audit_logs enable row level security;
revoke all on public.audit_logs from anon,authenticated;
grant select on public.audit_logs to authenticated;
alter table public.store_settings enable row level security;
revoke all on public.store_settings from anon,authenticated;
grant select on public.store_settings to authenticated;
alter table public.store_business_hours enable row level security;
revoke all on public.store_business_hours from anon,authenticated;
grant select on public.store_business_hours to authenticated;
alter table public.menu_categories enable row level security;
revoke all on public.menu_categories from anon,authenticated;
grant select on public.menu_categories to authenticated;
alter table public.menu_sizes enable row level security;
revoke all on public.menu_sizes from anon,authenticated;
grant select on public.menu_sizes to authenticated;
alter table public.menu_items enable row level security;
revoke all on public.menu_items from anon,authenticated;
grant select on public.menu_items to authenticated;
alter table public.menu_item_prices enable row level security;
revoke all on public.menu_item_prices from anon,authenticated;
grant select on public.menu_item_prices to authenticated;
alter table public.menu_borders enable row level security;
revoke all on public.menu_borders from anon,authenticated;
grant select on public.menu_borders to authenticated;
alter table public.menu_border_categories enable row level security;
revoke all on public.menu_border_categories from anon,authenticated;
grant select on public.menu_border_categories to authenticated;
alter table public.menu_border_prices enable row level security;
revoke all on public.menu_border_prices from anon,authenticated;
grant select on public.menu_border_prices to authenticated;
alter table public.delivery_settings enable row level security;
revoke all on public.delivery_settings from anon,authenticated;
grant select on public.delivery_settings to authenticated;
alter table public.delivery_neighborhood_fees enable row level security;
revoke all on public.delivery_neighborhood_fees from anon,authenticated;
grant select on public.delivery_neighborhood_fees to authenticated;
alter table public.delivery_distance_fees enable row level security;
revoke all on public.delivery_distance_fees from anon,authenticated;
grant select on public.delivery_distance_fees to authenticated;
alter table public.payment_methods enable row level security;
revoke all on public.payment_methods from anon,authenticated;
grant select on public.payment_methods to authenticated;
alter table public.campaigns enable row level security;
revoke all on public.campaigns from anon,authenticated;
grant select on public.campaigns to authenticated;
alter table public.coupons enable row level security;
revoke all on public.coupons from anon,authenticated;
grant select on public.coupons to authenticated;
alter table public.coupon_categories enable row level security;
revoke all on public.coupon_categories from anon,authenticated;
grant select on public.coupon_categories to authenticated;
alter table public.coupon_products enable row level security;
revoke all on public.coupon_products from anon,authenticated;
grant select on public.coupon_products to authenticated;
alter table public.customers enable row level security;
revoke all on public.customers from anon,authenticated;
grant select on public.customers to authenticated;
alter table public.customer_addresses enable row level security;
revoke all on public.customer_addresses from anon,authenticated;
grant select on public.customer_addresses to authenticated;
alter table public.whatsapp_instances enable row level security;
revoke all on public.whatsapp_instances from anon,authenticated;
grant select on public.whatsapp_instances to authenticated;
alter table public.conversations enable row level security;
revoke all on public.conversations from anon,authenticated;
grant select on public.conversations to authenticated;
alter table public.conversation_messages enable row level security;
revoke all on public.conversation_messages from anon,authenticated;
grant select on public.conversation_messages to authenticated;
alter table public.carts enable row level security;
revoke all on public.carts from anon,authenticated;
grant select on public.carts to authenticated;
alter table public.cart_items enable row level security;
revoke all on public.cart_items from anon,authenticated;
grant select on public.cart_items to authenticated;
alter table public.orders enable row level security;
revoke all on public.orders from anon,authenticated;
grant select on public.orders to authenticated;
alter table public.order_items enable row level security;
revoke all on public.order_items from anon,authenticated;
grant select on public.order_items to authenticated;
alter table public.order_status_history enable row level security;
revoke all on public.order_status_history from anon,authenticated;
grant select on public.order_status_history to authenticated;
alter table public.payments enable row level security;
revoke all on public.payments from anon,authenticated;
grant select on public.payments to authenticated;
alter table public.coupon_redemptions enable row level security;
revoke all on public.coupon_redemptions from anon,authenticated;
grant select on public.coupon_redemptions to authenticated;
alter table public.print_settings enable row level security;
revoke all on public.print_settings from anon,authenticated;
grant select on public.print_settings to authenticated;
alter table public.notifications enable row level security;
revoke all on public.notifications from anon,authenticated;
grant select on public.notifications to authenticated;
alter table public.notification_preferences enable row level security;
revoke all on public.notification_preferences from anon,authenticated;
grant select on public.notification_preferences to authenticated;
alter table public.team_invites enable row level security;
revoke all on public.team_invites from anon,authenticated;
grant select on public.team_invites to authenticated;
create policy tenants_read on public.tenants for select to authenticated using(private.member_of(id));
create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or exists(select 1 from public.tenant_members m where m.user_id=profiles.id and private.has_permission(m.tenant_id,'team.view')));
create policy members_read on public.tenant_members for select to authenticated using(private.member_of(tenant_id));
create policy permissions_read on public.permissions for select to authenticated using(true);
create policy role_permissions_read on public.role_permissions for select to authenticated using(true);
create policy member_permissions_read on public.member_permissions for select to authenticated using(private.member_of(tenant_id));
create policy plans_read on public.subscription_plans for select to authenticated using(active);
create policy subscriptions_read on public.subscriptions for select to authenticated using(private.has_permission(tenant_id,'subscription.view'));
create policy audit_read on public.audit_logs for select to authenticated using(private.has_permission(tenant_id,'audit.view') and private.subscription_active(tenant_id));
create policy store_settings_read on public.store_settings for select to authenticated using(private.has_permission(tenant_id,'settings.view') and private.subscription_active(tenant_id));
grant insert,update on public.store_settings to authenticated;
create policy store_settings_insert on public.store_settings for insert to authenticated with check(private.has_permission(tenant_id,'settings.edit') and private.subscription_active(tenant_id));
create policy store_settings_update on public.store_settings for update to authenticated using(private.has_permission(tenant_id,'settings.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'settings.edit') and private.subscription_active(tenant_id));
create policy store_business_hours_read on public.store_business_hours for select to authenticated using(private.has_permission(tenant_id,'settings.view') and private.subscription_active(tenant_id));
grant insert,update on public.store_business_hours to authenticated;
create policy store_business_hours_insert on public.store_business_hours for insert to authenticated with check(private.has_permission(tenant_id,'settings.edit') and private.subscription_active(tenant_id));
create policy store_business_hours_update on public.store_business_hours for update to authenticated using(private.has_permission(tenant_id,'settings.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'settings.edit') and private.subscription_active(tenant_id));
create policy menu_categories_read on public.menu_categories for select to authenticated using(private.has_permission(tenant_id,'menu.view') and private.subscription_active(tenant_id));
grant insert,update on public.menu_categories to authenticated;
create policy menu_categories_insert on public.menu_categories for insert to authenticated with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_categories_update on public.menu_categories for update to authenticated using(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_sizes_read on public.menu_sizes for select to authenticated using(private.has_permission(tenant_id,'menu.view') and private.subscription_active(tenant_id));
grant insert,update on public.menu_sizes to authenticated;
create policy menu_sizes_insert on public.menu_sizes for insert to authenticated with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_sizes_update on public.menu_sizes for update to authenticated using(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_items_read on public.menu_items for select to authenticated using(private.has_permission(tenant_id,'menu.view') and private.subscription_active(tenant_id));
grant insert,update on public.menu_items to authenticated;
create policy menu_items_insert on public.menu_items for insert to authenticated with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_items_update on public.menu_items for update to authenticated using(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_item_prices_read on public.menu_item_prices for select to authenticated using(private.has_permission(tenant_id,'menu.view') and private.subscription_active(tenant_id));
grant insert,update on public.menu_item_prices to authenticated;
create policy menu_item_prices_insert on public.menu_item_prices for insert to authenticated with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_item_prices_update on public.menu_item_prices for update to authenticated using(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_borders_read on public.menu_borders for select to authenticated using(private.has_permission(tenant_id,'menu.view') and private.subscription_active(tenant_id));
grant insert,update on public.menu_borders to authenticated;
create policy menu_borders_insert on public.menu_borders for insert to authenticated with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_borders_update on public.menu_borders for update to authenticated using(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_border_categories_read on public.menu_border_categories for select to authenticated using(private.has_permission(tenant_id,'menu.view') and private.subscription_active(tenant_id));
grant insert,update on public.menu_border_categories to authenticated;
create policy menu_border_categories_insert on public.menu_border_categories for insert to authenticated with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_border_categories_update on public.menu_border_categories for update to authenticated using(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_border_prices_read on public.menu_border_prices for select to authenticated using(private.has_permission(tenant_id,'menu.view') and private.subscription_active(tenant_id));
grant insert,update on public.menu_border_prices to authenticated;
create policy menu_border_prices_insert on public.menu_border_prices for insert to authenticated with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy menu_border_prices_update on public.menu_border_prices for update to authenticated using(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'menu.edit') and private.subscription_active(tenant_id));
create policy delivery_settings_read on public.delivery_settings for select to authenticated using(private.has_permission(tenant_id,'delivery.view') and private.subscription_active(tenant_id));
grant insert,update on public.delivery_settings to authenticated;
create policy delivery_settings_insert on public.delivery_settings for insert to authenticated with check(private.has_permission(tenant_id,'delivery.edit') and private.subscription_active(tenant_id));
create policy delivery_settings_update on public.delivery_settings for update to authenticated using(private.has_permission(tenant_id,'delivery.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'delivery.edit') and private.subscription_active(tenant_id));
create policy delivery_neighborhood_fees_read on public.delivery_neighborhood_fees for select to authenticated using(private.has_permission(tenant_id,'delivery.view') and private.subscription_active(tenant_id));
grant insert,update on public.delivery_neighborhood_fees to authenticated;
create policy delivery_neighborhood_fees_insert on public.delivery_neighborhood_fees for insert to authenticated with check(private.has_permission(tenant_id,'delivery.edit') and private.subscription_active(tenant_id));
create policy delivery_neighborhood_fees_update on public.delivery_neighborhood_fees for update to authenticated using(private.has_permission(tenant_id,'delivery.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'delivery.edit') and private.subscription_active(tenant_id));
create policy delivery_distance_fees_read on public.delivery_distance_fees for select to authenticated using(private.has_permission(tenant_id,'delivery.view') and private.subscription_active(tenant_id));
grant insert,update on public.delivery_distance_fees to authenticated;
create policy delivery_distance_fees_insert on public.delivery_distance_fees for insert to authenticated with check(private.has_permission(tenant_id,'delivery.edit') and private.subscription_active(tenant_id));
create policy delivery_distance_fees_update on public.delivery_distance_fees for update to authenticated using(private.has_permission(tenant_id,'delivery.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'delivery.edit') and private.subscription_active(tenant_id));
create policy payment_methods_read on public.payment_methods for select to authenticated using(private.has_permission(tenant_id,'payments.view') and private.subscription_active(tenant_id));
grant insert,update on public.payment_methods to authenticated;
create policy payment_methods_insert on public.payment_methods for insert to authenticated with check(private.has_permission(tenant_id,'payments.manage') and private.subscription_active(tenant_id));
create policy payment_methods_update on public.payment_methods for update to authenticated using(private.has_permission(tenant_id,'payments.manage') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'payments.manage') and private.subscription_active(tenant_id));
create policy campaigns_read on public.campaigns for select to authenticated using(private.has_permission(tenant_id,'campaigns.view') and private.subscription_active(tenant_id));
grant insert,update on public.campaigns to authenticated;
create policy campaigns_insert on public.campaigns for insert to authenticated with check(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id));
create policy campaigns_update on public.campaigns for update to authenticated using(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id));
create policy coupons_read on public.coupons for select to authenticated using(private.has_permission(tenant_id,'campaigns.view') and private.subscription_active(tenant_id));
grant insert,update on public.coupons to authenticated;
create policy coupons_insert on public.coupons for insert to authenticated with check(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id));
create policy coupons_update on public.coupons for update to authenticated using(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id));
create policy coupon_categories_read on public.coupon_categories for select to authenticated using(private.has_permission(tenant_id,'campaigns.view') and private.subscription_active(tenant_id));
grant insert,update on public.coupon_categories to authenticated;
create policy coupon_categories_insert on public.coupon_categories for insert to authenticated with check(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id));
create policy coupon_categories_update on public.coupon_categories for update to authenticated using(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id));
create policy coupon_products_read on public.coupon_products for select to authenticated using(private.has_permission(tenant_id,'campaigns.view') and private.subscription_active(tenant_id));
grant insert,update on public.coupon_products to authenticated;
create policy coupon_products_insert on public.coupon_products for insert to authenticated with check(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id));
create policy coupon_products_update on public.coupon_products for update to authenticated using(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'campaigns.edit') and private.subscription_active(tenant_id));
create policy customers_read on public.customers for select to authenticated using(private.has_permission(tenant_id,'customers.view') and private.subscription_active(tenant_id));
grant insert,update on public.customers to authenticated;
create policy customers_insert on public.customers for insert to authenticated with check(private.has_permission(tenant_id,'customers.edit') and private.subscription_active(tenant_id));
create policy customers_update on public.customers for update to authenticated using(private.has_permission(tenant_id,'customers.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'customers.edit') and private.subscription_active(tenant_id));
create policy customer_addresses_read on public.customer_addresses for select to authenticated using(private.has_permission(tenant_id,'customers.view') and private.subscription_active(tenant_id));
grant insert,update on public.customer_addresses to authenticated;
create policy customer_addresses_insert on public.customer_addresses for insert to authenticated with check(private.has_permission(tenant_id,'customers.edit') and private.subscription_active(tenant_id));
create policy customer_addresses_update on public.customer_addresses for update to authenticated using(private.has_permission(tenant_id,'customers.edit') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'customers.edit') and private.subscription_active(tenant_id));
create policy whatsapp_instances_read on public.whatsapp_instances for select to authenticated using(private.has_permission(tenant_id,'whatsapp.view') and private.subscription_active(tenant_id));
create policy conversations_read on public.conversations for select to authenticated using(private.has_permission(tenant_id,'conversations.view') and private.subscription_active(tenant_id));
create policy conversation_messages_read on public.conversation_messages for select to authenticated using(private.has_permission(tenant_id,'conversations.view') and private.subscription_active(tenant_id));
create policy carts_read on public.carts for select to authenticated using(private.has_permission(tenant_id,'conversations.view') and private.subscription_active(tenant_id));
create policy cart_items_read on public.cart_items for select to authenticated using(private.has_permission(tenant_id,'conversations.view') and private.subscription_active(tenant_id));
create policy orders_read on public.orders for select to authenticated using(private.has_permission(tenant_id,'orders.view') and private.subscription_active(tenant_id));
create policy order_items_read on public.order_items for select to authenticated using(private.has_permission(tenant_id,'orders.view') and private.subscription_active(tenant_id));
create policy order_status_history_read on public.order_status_history for select to authenticated using(private.has_permission(tenant_id,'orders.view') and private.subscription_active(tenant_id));
create policy payments_read on public.payments for select to authenticated using(private.has_permission(tenant_id,'orders.view') and private.subscription_active(tenant_id));
create policy coupon_redemptions_read on public.coupon_redemptions for select to authenticated using(private.has_permission(tenant_id,'campaigns.view') and private.subscription_active(tenant_id));
create policy print_settings_read on public.print_settings for select to authenticated using(private.has_permission(tenant_id,'printing.view') and private.subscription_active(tenant_id));
grant insert,update on public.print_settings to authenticated;
create policy print_settings_insert on public.print_settings for insert to authenticated with check(private.has_permission(tenant_id,'printing.manage') and private.subscription_active(tenant_id));
create policy print_settings_update on public.print_settings for update to authenticated using(private.has_permission(tenant_id,'printing.manage') and private.subscription_active(tenant_id)) with check(private.has_permission(tenant_id,'printing.manage') and private.subscription_active(tenant_id));
create policy notifications_read on public.notifications for select to authenticated using(private.has_permission(tenant_id,'notifications.view') and private.subscription_active(tenant_id) and user_id=auth.uid() and private.has_permission(tenant_id,required_permission));
create policy notification_preferences_read on public.notification_preferences for select to authenticated using(private.has_permission(tenant_id,'notifications.view') and private.subscription_active(tenant_id) and user_id=auth.uid());
create policy team_invites_read on public.team_invites for select to authenticated using(private.has_permission(tenant_id,'team.view') and private.subscription_active(tenant_id));

create table private.integration_credentials(tenant_id uuid not null references public.tenants(id), provider text not null, encrypted_secret text not null, external_account_id text, created_at timestamptz default now(), primary key(tenant_id,provider));
create table private.webhook_events(id uuid primary key default gen_random_uuid(), provider text not null, event_key text not null, tenant_id uuid references public.tenants(id), payload jsonb not null, status text not null default 'pending', attempts integer not null default 0, available_at timestamptz not null default now(), locked_at timestamptz, error_code text, created_at timestamptz not null default now(), unique(provider,event_key));
create table private.outbox(id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), kind text not null, event_key text not null unique, payload jsonb not null, status text not null default 'pending', attempts integer not null default 0, available_at timestamptz not null default now(), locked_at timestamptz, created_at timestamptz not null default now());
create index outbox_pending on private.outbox(status,available_at);
create index webhooks_pending on private.webhook_events(status,available_at);
create table private.rate_limits(key text primary key, count integer not null, expires_at timestamptz not null);
create table private.geo_cache(key text primary key, tenant_id uuid not null references public.tenants(id), value jsonb not null, expires_at timestamptz not null);
create table private.push_subscriptions(id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), user_id uuid not null references public.profiles(id), endpoint text not null, p256dh text not null, auth text not null, created_at timestamptz default now(), unique(tenant_id,user_id,endpoint));
create table private.billing_charges(id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), subscription_id uuid not null references public.subscriptions(id), provider_id text unique, idempotency_key uuid not null default gen_random_uuid(), amount_cents integer not null, status text not null default 'pending', pix_copy_paste text, hosted_url text, expires_at timestamptz, credited_at timestamptz, created_at timestamptz not null default now());
create unique index billing_open_charge on private.billing_charges(tenant_id) where status in ('pending','creating');
create table private.support_sessions(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), tenant_id uuid not null references public.tenants(id), reason text not null, expires_at timestamptz not null, ended_at timestamptz, created_at timestamptz default now());
revoke all on all tables in schema private from public,anon,authenticated;
-- Only selected, tenant-scoped tables participate in realtime.
do $$ declare n text; begin
 if exists(select 1 from pg_publication where pubname='supabase_realtime') then
  foreach n in array array['orders','conversations','conversation_messages','notifications','whatsapp_instances','tenant_members'] loop
   if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=n) then execute format('alter publication supabase_realtime add table public.%I',n); end if;
  end loop;
 end if;
end $$;
